### ISSUE TITLE
OSError while importing pytorch_lightning on colab

### ISSUE THREAD

**Issue by sanspareilsmyn** [full-stack-deep-learning/fsdl-text-recognizer-2022#61]
While running lab02a_lightning.ipynb on colab, I encountered an error on importing pytorch_lightning.
Below is captured image of error I've met.
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/52681837/206891400-77af1d2e-9ac8-460e-9667-9e18bb944bee.png">

Seems that current environment.yml has a compatiblity issue with pytorch new release.
```
pip install -U torchtext
```
command fixed the issue though.

**Comment by charlesfrye** [comment]
thanks for reporting!

turns out, Colab updated a number of libraries all at once, because they updated Python to 3.8, so it took us some time to fix this one.

all should be gucci now, please reopen if you're still having issues
